### ISSUE TITLE
Missing model file `cky_classifier_ungrounded`

### ISSUE THREAD

**Issue by SivilTaram** [benbogin/glt-grounded-latent-trees-qa#1]
Hi Bogin,

   Many thanks for your contributions & efforts on open-sourcing such an elegant code base for compositional generalization. We want to have a try on the dummy arithmetic experiments, but I find that `cky_classifier_ungrounded` in `glt_arithemetic.jsonnet` seems to be missing. Do you mind sharing it here (it is ok if it cannot be run successfully)? I believe it would bring a lot of insights when I investigate the details. Thanks in advance.

Best Regards,
Qian

**Comment by benbogin** [comment]
Hi Qian, sure, I've just added the missing file and updated the readme file with running instructions. You should be able to replicate the results from the paper.
